version: "3.8"

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    environment:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    env_file:
      - .env
    expose:
      - "9000"
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mariadb
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "3306"

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
    name: mariadb_vol
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
    name: wordpress_vol

networks:
  inception:
    name: inception
    driver: bridge
