version: "3.8"

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception_network
    environment:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mysql
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    expose:
      - "9000"
  
  mysql:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    restart: always
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    expose:
      - "3306"

volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
    name: mysql_vol
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
    name: wordpress_vol

networks:
  inception_network:
    driver: bridge
