version: "3.8"

# definition fo services
services:
  # nginx
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception_network
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mysql
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
  
  mysql:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env

volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/falmeida/data/database
      o: bind
    name: mysql_vol
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/falmeida/data/wordpress
      o: bind
    name: wordpress_vol

networks:
  inception_network:
    driver: bridge
