version: "3.8"

# definition fo services
services:
  # nginx
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - "9000:9000"
    networks:
      - inception_network
# definition fo network
networks:
  inception_network:
    driver: bridge
